// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pygrpc.proto

package com.example.grpc;

public final class ProtoService {
  private ProtoService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pygrpc_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pygrpc_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pygrpc_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pygrpc_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pygrpc_Request1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pygrpc_Request1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pygrpc_Response1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pygrpc_Response1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014pygrpc.proto\022\006pygrpc\"\032\n\007Request\022\017\n\007mes" +
      "sage\030\001 \001(\t\"\033\n\010Response\022\017\n\007message\030\001 \001(\t\"" +
      "\033\n\010Request1\022\017\n\007message\030\001 \001(\t\"\034\n\tResponse" +
      "1\022\017\n\007message\030\001 \001(\t2\204\001\n\rPythonService\0227\n\020" +
      "callPythonMethod\022\017.pygrpc.Request\032\020.pygr" +
      "pc.Response\"\000\022:\n\021callPythonMethod2\022\020.pyg" +
      "rpc.Request1\032\021.pygrpc.Response1\"\000B\"\n\020com" +
      ".example.grpcB\014ProtoServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pygrpc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pygrpc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pygrpc_Request_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_pygrpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pygrpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pygrpc_Response_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_pygrpc_Request1_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pygrpc_Request1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pygrpc_Request1_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_pygrpc_Response1_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pygrpc_Response1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pygrpc_Response1_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
