// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pygrpc.proto

package com.example.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pygrpc.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
